### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seat_summary'

### ISSUE THREAD

**Issue by speedboattoyota** [charlestudor/PokerNowLogConverter#10]
[log_110223.csv](https://github.com/charlestudor/PokerNowLogConverter/files/10719815/log_110223.csv)
Hi - I received the error above with the attached log file. Previously it was working fine. Can you please take a look?

**Comment by charlestudor** [comment]
Hey speedboat,

Of course, thanks for uploading the log. I'll have a look when I next get a
chance.

-C

**Comment by charlestudor** [comment]
Hi again!

Just had a look at this, that's a funny bug - it looks like the parser isn't very resilient to certain player names, in particular it doesn't like the name "pennyfolds" currently!

Thanks for finding it, I'll improve how it handles player names but perhaps not until the weekend. Until then if you'd like to fix this log you should be able to just open the csv file in a text editor, find and replace all: "pennyfolds" -> "penny", save and try the converter again. If you need to preserve the name "pennyfolds", you could then add an alias by adding the flag "-a pennyfolds=penny".

Cheers,
-C

**Comment by speedboattoyota** [comment]
ok thanks appreciate it, I'll try that and see if it works.

**Comment by charlestudor** [comment]
Going to resolve this issue as most names that don't include double quotes in them will have no issue thanks to the change in PR #15 .

In the case of names with quotes, a much larger refactor would be necessary. Please reopen if this is massively important to someone! (But if you need a quick fix, you can always manually Find + Replace strange names in the raw log before running the converter)
