### ISSUE TITLE
New to python and hand history conversion. Need help

### ISSUE THREAD

**Issue by MikePhan89** [charlestudor/PokerNowLogConverter#11]
I have successfully downloaded python and this converter, but I don't know how to use it. I have no idea what to type for filename and am very confused about usage in general. Is there an example input I can follow? Sorry for the inconvenience, but I am a newbie. Thanks.

**Comment by charlestudor** [comment]
Hey Mike,

Apologies, I only just saw your message! If you are still wanting to use the tool and are not had any luck please reopen/reply to this issue and I will walk you through it!

Thanks,
Charles
