### ISSUE TITLE
Log FIle unable to convert

### ISSUE THREAD

**Issue by Veltridze** [charlestudor/PokerNowLogConverter#6]
Unable to covert this log file
[poker_now_log_pglK8iiIuo6_Lg6ygYFMPYMsV.csv](https://github.com/charlestudor/PokerNowLogConverter/files/9203799/poker_now_log_pglK8iiIuo6_Lg6ygYFMPYMsV.csv)

**Comment by charlestudor** [comment]
I'll check it out!

**Comment by charlestudor** [comment]
Hey @Veltridze. Thanks for reporting the issue. It should be fixed now, please check out the new release v0.0.7.

Let me know if you have any other problems!
