### ISSUE TITLE
Antes not being recognised/converted

### ISSUE THREAD

**Issue by Beermagic** [charlestudor/PokerNowLogConverter#9]
I managed to convert a log to a text file using the tool but when attempting to upload to PT4 I get an "invalid pot size/winnings" error which seems to be caused when we introduced antes to the blind structure; the converter doesn't look like it reads the antes and when PT4 compares how much was put in the pot with how much was reported to have been won they don't match and so it fails to upload the hand. The antes were introduced at line 6172 of the csv file and the first error is reported at line #472 of the converted log (and every subsequent hand). I've attached both files.

[poker_now_log.csv](https://github.com/charlestudor/PokerNowLogConverter/files/10286487/poker_now_log.csv)
[ConvertedPNLog-2022-12-19-2002-25.0-50.0-Hold'em No Limit.txt](https://github.com/charlestudor/PokerNowLogConverter/files/10286488/ConvertedPNLog-2022-12-19-2002-25.0-50.0-Hold.em.No.Limit.txt)

I really appreciate what you've done here and am going to try to understand how it all works - I am completely new to programming - but if there's anything you can do to help that would be really useful.

**Comment by charlestudor** [comment]
Hey Beermagic!

Thanks for reporting the issue! Antes are definitely less tested than other
things, because I usually play without them!
Thanks for uploading a log, I will check it out when I get a chance and get
back to you.

Cheers,
Charles

**Comment by charlestudor** [comment]
Hey Beer!

I've just added a new version v0.0.10 that should support antes better. I tried importing your hands into PT4 and it succeeded on most of them. 

Unfortunately there are still some failing hands and I can't for the life of me work out the pattern. It could well have nothing to do with antes, probably some small formatting issue. If you can spot the difference between the failing hands and the successful ones please let me know, I'll have another go at some point. Until then I hope it's still useful to have the majority working.

Cheers,
Charles

**Comment by charlestudor** [comment]
Actually, although the hands say they are importing in PT4, they don't seem to be showing up properly. I'll investigate when I get a chance!

**Comment by Beermagic** [comment]
Wow Charles, that's fantastic! Thank you so much for that. It worked perfectly for me for every hand once I'd used an alias for a player that rejoined the game a couple of times.
Thanks again for your work on this.
Cheers
Beermagic
    On Friday, 23 December 2022 at 00:06:03 GMT, Charles Tudor ***@***.***> wrote:  
 
 


Hey Beer!

I've just added a new version v0.0.10 that should support antes better. I tried importing your hands into PT4 and it succeeded on most of them.

Unfortunately there are still some failing hands and I can't for the life of me work out the pattern. It could well have nothing to do with antes, probably some small formatting issue. If you can spot the difference between the failing hands and the successful ones please let me know, I'll have another go at some point. Until then I hope it's still useful to have the majority working.

Cheers,
Charles

**Comment by charlestudor** [comment]
That's great news! Maybe there was an issue with my PT4 database then instead.

I'll close the issue, but if you or anyone else reading this has a converted log which isn't being imported correctly, don't hesitate to open a new issue, attach the log and I'll take a look.

Good luck with the games!
-C
